### ISSUE TITLE
ESRGAN-Training

### ISSUE THREAD

**Issue by Satyajit1993** [Lornatang/ESRGAN-PyTorch#19]
For my own 128*128 image dataset

TypeError: 'type' object is not subscriptable

**Comment by Lornatang** [comment]
Can you give me more detail errors log? Example, call command and error line.

**Comment by Lornatang** [comment]
Please check if the data is None when executing the random_rotate function?

**Comment by rajeshkont** [comment]
yeah, line in the code is as follows:
def random_rotate(image,
                  angles: list,
                  center: tuple[int, int] = None,
                  scale_factor: float = 1.0) -> np.ndarray:
which was given the previously mentioned error.

Understanding that the tuple can't have any assignment like that, for now I had changed
 center: tuple[int, int] = None
 to 
 center: tuple = None
 
 For now it has moved forward. But I am not sure what kind of issue will it bring. 
 I ask again, was there something I had to take care while implementing the downloaded code, because only I seem to get this error.

**Comment by Lornatang** [comment]
Generally, the center is None, only set the angles parameters~

**Comment by Lornatang** [comment]
@rajeshkont @Satyajit1993 Would it be convenient for you to send me a copy of the prepared dataset? via google drive form? so that I can check for errors~

**Comment by Satyajit1993** [comment]
For VDSR successfully trained and generated bast.pth but while doing the
mode valid and running validate.py sr_image cant be saved under result
folder

and

For other models, i was able to resolve the tensor a 512 and tensor b 128
issues but now I am facing error like


ModuleNotFoundError: No module named 'torchvision.models.feature_extraction'

my torchvision is 0.8.2 cuda 11.0 cudnn 8.0.5



I want to use your models where my HR images are of 512*512 and LR images
are of 128*128 dimension

**Comment by Lornatang** [comment]
@Satyajit1993 Upgrade torch >=1.12.0 ~
